import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layouts/Header";

export const metadata: Metadata = {
  title: "TodoApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <main className="flex-1 pt-[60px] grid max-w-[700px] min-h-[calc(100vh_-_1rem)] divide-y p-4 text-sm lg:min-h-[calc(100vh_-_1.5rem)]">
          {children}
        </main>
      </body>
    </html>
  );
}
